// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1NSrti-WfDLVzfSt3nFuDnkeswvZm6hU',
    appId: '1:836963118618:web:db64fdc2c480cafc11aba3',
    messagingSenderId: '836963118618',
    projectId: 'elssa-e4ed1',
    authDomain: 'elssa-e4ed1.firebaseapp.com',
    storageBucket: 'elssa-e4ed1.firebasestorage.app',
    measurementId: 'G-4NVESSW46R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPdapTnnzGACzjuRGpIknFjqBYrYcB9pA',
    appId: '1:836963118618:android:7b95d358ba73f4b311aba3',
    messagingSenderId: '836963118618',
    projectId: 'elssa-e4ed1',
    storageBucket: 'elssa-e4ed1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsd1MnoODmrSV73-bGYcPD4ReoFlkHdIk',
    appId: '1:836963118618:ios:96d6b2746f5005d011aba3',
    messagingSenderId: '836963118618',
    projectId: 'elssa-e4ed1',
    storageBucket: 'elssa-e4ed1.firebasestorage.app',
    iosClientId: '836963118618-hl3q12caebfrr9g6hm0tbskqeqa85f2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.elssaAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsd1MnoODmrSV73-bGYcPD4ReoFlkHdIk',
    appId: '1:836963118618:ios:96d6b2746f5005d011aba3',
    messagingSenderId: '836963118618',
    projectId: 'elssa-e4ed1',
    storageBucket: 'elssa-e4ed1.firebasestorage.app',
    iosClientId: '836963118618-hl3q12caebfrr9g6hm0tbskqeqa85f2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.elssaAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1NSrti-WfDLVzfSt3nFuDnkeswvZm6hU',
    appId: '1:836963118618:web:9be1bf3ed0a86f5011aba3',
    messagingSenderId: '836963118618',
    projectId: 'elssa-e4ed1',
    authDomain: 'elssa-e4ed1.firebaseapp.com',
    storageBucket: 'elssa-e4ed1.firebasestorage.app',
    measurementId: 'G-RT0S1SD9YK',
  );

}